### ISSUE TITLE
Accept header not receiving on payeefsp side even though the payerfsp is sending it

### ISSUE THREAD

**Issue by sri-miriyala** [mojaloop/mojaloop#239] opened 2020-01-06 15:04 UTC
When sending GET /parties call, ACCEPT header with value "application/vnd.interoperability.parties+json;version=1" is sent from Postman as payerfsp. But I do not see it coming from PUT to the payerfsp. When I further look into the logs, the payeefsp is not receiving this header in the request itself.

**Steps to reproduce:**
1. Run the first three requests from here:
<img width="499" alt="Screen Shot 2020-01-06 at 10 00 28 AM" src="https://user-images.githubusercontent.com/38143240/71826210-6b6a8b80-306b-11ea-90db-468b27fbfb3f.png">
2. Check the response coming back which has no accept header.
3. Below screenshot shows the console output at payeefsp that says ACCEPT header not received at payeefsp.

Request:
curl -X GET \
  http://dev1-account-lookup.mojaloop.live/parties/MSISDN/17039811907 \
  -H 'Accept: application/vnd.interoperability.parties+json;version=1' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/vnd.interoperability.parties+json;version=1.0' \
  -H 'Date: Mon, 18 Nov 2019 17:12:39 GMT' \
  -H 'FSPIOP-Source: payerfsp' \
  -H 'Host: dev1-account-lookup.mojaloop.live' \
  -H 'Postman-Token: f2a14d26-63bd-43cc-88c7-8e2becfaa75e,96d30bff-222e-4c8a-9cd0-c28d7924f5a8' \
  -H 'User-Agent: PostmanRuntime/7.20.1' \
  -H 'cache-control: no-cache'

Response (request at payeefsp):
<img width="651" alt="Screen Shot 2020-01-06 at 9 59 19 AM" src="https://user-images.githubusercontent.com/38143240/71826124-41b16480-306b-11ea-8ed8-da4c08f453d2.png">

Component: Interop switch
Version: 8.4.0
Bug raised by : Sri

**Comment by elnyry** [comment] 2020-01-15 09:05
@sri-miriyala: Is this duplicate of - https://github.com/mojaloop/project/issues/1149 ?

**Closed** 2020-04-01 10:42 UTC
Labels: duplicate
